[[rules]]
id = "worktree-add"
checker = ["new-feature", "check-rule", "worktree-add"]

[[rules]]
id = "worktree-remove"
checker = ["new-feature", "check-rule", "worktree-remove"]

[[rules]]
id = "target-branch"
checker = ["new-feature", "check-rule", "target-branch"]

[[rules]]
id = "target-merge"
checker = ["new-feature", "check-rule", "target-merge"]
